petstore/Controllers/QLDonHangController.cs
using PagedList;
using petstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace petstore.Controllers
{
    public class QLDonHangController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();

        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;

            var all_danhmuc = from tt in data.DonHangs select tt;

            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_danhmuc.ToPagedList(pageNum, pageSize));

        }

        [HttpPost]
        public ActionResult Index(FormCollection collection, int? page)
        {
            if (page == null) page = 1;
            var ngaydat = DateTime.Parse(collection["DonTheoNgay"].ToString());

            var all_danhmuc = (from tt in data.DonHangs where tt.ngaydat == ngaydat select tt);
            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_danhmuc.ToPagedList(pageNum, pageSize));
        }

        //---------Detail-------------

        public ActionResult DetailsCTDH(int id)
        {
            var results = (from t1 in data.ChiTietDonHangs
                           join t2 in data.DonHangs
                           on new { t1.madon } equals
                               new { t2.madon }
                           where t2.madon == id
                           select t1).ToList();

            List<KhachHang> khachhang = data.KhachHangs.ToList();
            List<DonHang> donhang = data.DonHangs.ToList();

            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            List<SanPham> sanpham = data.SanPhams.ToList();

            var ViewKH = from kh in khachhang
                         join dh in donhang
    on kh.makh equals dh.makh
                         where dh.madon == id && kh.makh == dh.makh
                         select new ViewModel
                         {
                             khachhang = kh,
                             donhang = dh
                         };

            var ViewSP = from sp in sanpham
                         join ct in ctdh
      on sp.masp equals ct.masp
                         where ct.madon == id && sp.masp == ct.masp
                         select new ViewModel
                         {
                             sanpham = sp,
                             ctdh = ct
                         };


            ViewBag.ViewChiTietDH = ViewKH;
            ViewBag.ViewSP = ViewSP;

            return View(results);
        }

        //---------Edit-Don Hang------------

        public ActionResult Edit(int id)
        {
            var E_category = data.DonHangs.First(m => m.madon == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var danhmuc = data.DonHangs.First(m => m.madon == id);
            var E_tendanhmuc = collection["giaohang"];
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            danhmuc.madon = id;
            if (string.IsNullOrEmpty(E_tendanhmuc))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                danhmuc.giaohang = E_tendanhmuc;
                danhmuc.ngaygiao = DateTime.Parse(ngaygiao);
                UpdateModel(danhmuc);

                if (E_tendanhmuc == "giao thành công")
                {
                    var ctdh = data.ChiTietDonHangs.Where(m => m.madon == id).ToList();
                    foreach (var item in ctdh)
                    {
                        item.status = 1;
                        UpdateModel(item);
                    }
                }
                else
                {
                    var ctdh = data.ChiTietDonHangs.Where(m => m.madon == id).ToList();
                    foreach (var item in ctdh)
                    {
                        item.status = 0;
                        UpdateModel(item);
                    }
                }

                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        //---------Delete------------

        public ActionResult Delete(int id)
        {
            var D_danhmuc = data.DonHangs.FirstOrDefault(n => n.madon == id);
            return View(D_danhmuc);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var D_danhmuc2 = data.ChiTietDonHangs.Where(m => m.madon == id).First();
                data.ChiTietDonHangs.DeleteOnSubmit(D_danhmuc2);
                data.SubmitChanges();

                var D_danhmuc = data.DonHangs.Where(m => m.madon == id).First();
                data.DonHangs.DeleteOnSubmit(D_danhmuc);
                data.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e) { return View("Error" + e); }

        }

    }
}

petstore/Views/QLDonHang/Delete.cshtml
@model petstore.Models.DonHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 padding-8">
    <h2>Xóa đơn hàng</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.thanhtoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.thanhtoan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.giaohang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.giaohang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ngaydat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ngaydat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ngaygiao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ngaygiao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.makh)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.makh)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>

</div>


petstore/Views/QLDonHang/DetailsCTDH.cshtml
@model IEnumerable<petstore.Models.ChiTietDonHang>

@{
    ViewBag.Title = "DetailsCTDH";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 padding-8 ViewPrint">

    <h3>Thông tin khách hàng</h3>
    @foreach (var m in ViewBag.ViewChiTietDH)
    {
        <h5>Họ tên: @m.khachhang.hoten</h5>
        <h5>Email: @m.khachhang.email</h5>
        <h5>Địa chỉ: @m.khachhang.diachi</h5>
        <h5>Số điện thoại: @m.khachhang.dienthoai</h5>
    }

    <h2>Chi tiết sản phẩm</h2>

    <table class="table">
        <tr>
            <th>mã đơn</th>
            <th>tên sp</th>
            <th>hình</th>
            <th>giá</th>
            <th>giảm giá</th>
            <th>giá km</th>
            <th>số lượng</th>
        </tr>

        @foreach (var item in ViewBag.ViewSP)
        {
            <tr>
                <td>
                    @item.ctdh.madon
                </td>
                <td>
                    @item.sanpham.tensp
                </td>
                <td>
                    <img src=" @item.sanpham.hinh" height="100px" />
                </td>
                <td>@item.sanpham.giaban vnđ</td>
                <td>
                    @item.sanpham.giamgia %
                </td>
                <td>
                    @String.Format("{0:N0}", @item.sanpham.giakhuyenmai) vnđ
                </td>

                <td>
                    @item.ctdh.soluong
                </td>

            </tr>
        }

    </table>

    @foreach (var item in Model.Take(1))
    {
        <tr>
            <td>
                <strong> Tổng số lượng</strong>

                @Html.DisplayFor(modelItem => item.tongsoluong)
            </td>
            <td>
                <strong> Tổng giá tiền</strong>

                @String.Format("{0:N0}", item.tonggia) vnđ
            </td>

        </tr>
    }


</div>

<div class="body padding-8" style="border: none; box-shadow: none; border-radius: none; margin-top: 10px;">
    <div>
        <button id="Print" class="btn btn-primary">Print</button>
    </div>

    <div class="mt-2">
        @Html.ActionLink("Quay lại", "Index")
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="~/Content/admin/js/printThis.js"></script>


<script>
    jQuery(document).ready(function ($) {
        $('#Print').on("click", function () {
            $('.ViewPrint').printThis({
                debug: false,               // show the iframe for debugging
                importCSS: true,            // import parent page css
                importStyle: false,         // import style tags
                printContainer: true,       // print outer container/$.selector
                loadCSS: "",                // path to additional css file - use an array [] for multiple
                pageTitle: "",              // add title to print page
                removeInline: false,        // remove inline styles from print elements
                removeInlineSelector: "*",  // custom selectors to filter inline styles. removeInline must be true
                printDelay: 333,            // variable print delay
                header: null,               // prefix to html
                footer: null,               // postfix to html
                base: false,                // preserve the BASE tag or accept a string for the URL
                formValues: true,           // preserve input/form values
                canvas: false,              // copy canvas content
                doctypeString: '...',       // enter a different doctype for older markup
                removeScripts: false,       // remove script tags from print content
                copyTagClasses: false,      // copy classes from the html & body tag
                beforePrintEvent: null,     // function for printEvent in iframe
                beforePrint: null,          // function called before iframe is filled
                afterPrint: null            // function called before iframe is removed
            });
        });
    });
</script>

petstore/Views/QLDonHang/Edit.cshtml
@model petstore.Models.DonHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 padding-8">
    <h2>Sửa đơn hàng</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.madon)

    <div class="form-group">
        <label class="control-label col-md-2">Mã KH</label>
        <div class="col-md-10">
            <div class="form-control">@Model.makh</div>
            @Html.ValidationMessageFor(model => model.makh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.thanhtoan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="form-control">@Model.thanhtoan</div>
            @Html.ValidationMessageFor(model => model.thanhtoan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="giaohang" class="control-label col-md-2">trạng thái:</label>
        <div class="col-md-10">
            <select name="giaohang" id="cars" class="form-control">
                <option checked>@Model.giaohang</option>
                <option value="chờ xử lý">1 - chờ xử lý</option>
                <option value="đang xử lý">2 - đang xử lý</option>
                <option value="đang giao">3 - đang giao</option>
                <option value="giao thành công">4 - giao thành công</option>
                <option value="hủy">5 - hủy</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Ngày Đặt</label>
        <div class="col-md-10">
            <div class="form-control">@Model.ngaydat</div>
            @Html.ValidationMessageFor(model => model.ngaydat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ngaygiao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="date" name="NgayGiao" required />
            @Html.ValidationMessageFor(model => model.ngaygiao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-actions no-color ml-2">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
    </div>
</div>
    }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>



petstore/Views/QLDonHang/Index.cshtml
@model PagedList.IPagedList<petstore.Models.DonHang>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 padding-8">
    <div class="d-flex justify-content-between">
        <h2>Quản lý đơn hàng</h2>
        @using (Html.BeginForm("Index", "QLDonHang", FormMethod.Post))
        {
            <h3>Tìm kiếm đơn theo ngày đặt</h3>
            <input type="date" name="DonTheoNgay" required />

            <input type="submit" value="Kiểm tra" />
        }
    </div>

    <div class="body fix-width scroll-inner">
        <table class="table table-striped">
            <tr>
                <th>
                    Mã kh
                </th>
                <th>
                    Thanh toán
                </th>
                <th>
                    Trạng thái
                </th>
                <th>
                    Ngày đặt
                </th>
                <th>
                    Ngày giao
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.makh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.thanhtoan)
                    </td>
                    <td>
                        @if (item.giaohang == "chờ xử lý")
                        {
                            <div style="color: #007bff;">@item.giaohang</div>
                        }
                        else if (item.giaohang == "đang xử lý")
                        {
                            <div style="color: orange;">@item.giaohang</div>
                        }
                        else if (item.giaohang == "đang giao")
                        {
                            <div style="color: forestgreen;">@item.giaohang</div>
                        }
                        else if (item.giaohang == "giao thành công")
                        {
                            <div style="color: green;">@item.giaohang</div>
                        }
                        else if (item.giaohang == "hủy")
                        {
                            <div style="color: red;">@item.giaohang</div>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ngaydat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ngaygiao)
                    </td>

                    <td>
                        <a href="@Url.Action("DetailsCTDH", new { id = item.madon })" class="text-primary f2"><i class="fa-solid fa-eye"></i></a>&nbsp;
                        <a href="@Url.Action("Edit", new { id = item.madon })" class="text-primary f2"><i class="fas fa-edit"></i></a>&nbsp;
                        <a href="@Url.Action("Delete", new { id = item.madon })" class="text-primary f2"><i class="fa-solid fa-trash-can"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>

        <div class="d-flex justify-content-center mt-3">
            <div class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("Index", new
                {
                    page = page
                }))
            </div>
        </div>

        <div>
            @Html.ActionLink("Quay Lại", "Index", "QLDonHang")
        </div>
    </div>
