petstore/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using petstore.Models;
using System.Security.Cryptography;
using System.Text;
using petstore.Common;
using System.Net.Mail;
using System.Net;

namespace petstore.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        MyDataDataContext data = new MyDataDataContext();

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();

        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var tendangnhap = collection["tendangnhap"];

            var matkhau1 = collection["matkhau"];
            var matkhau = Encryptor.MD5Hash(matkhau1);

            MyDataDataContext data = new MyDataDataContext();
            var dblist = data.KhachHangs.ToList();


            if (matkhau1.Length < 6)
            {
                ViewData["Length>6"] = "Mật khẩu phải dài hơn 5 kí tự";
            }
            else if (hoten.Length < 4)
            {
                ViewData["hoten>3"] = "Họ tên phải dài hơn 3 kí tự";
            }
            else if (tendangnhap.Length < 4)
            {
                ViewData["tendangnhap>3"] = "Tên đăng nhập phải dài hơn 3 kí tự";
            }
            else
            {
                var MatKhauXacNhan1 = collection["MatKhauXacNhan"];
                var MatKhauXacNhan = Encryptor.MD5Hash(MatKhauXacNhan1);

                var email = collection["email"];
                var diachi = collection["diachi"];
                var dienthoai = collection["dienthoai"];
                var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
                if (String.IsNullOrEmpty(MatKhauXacNhan))
                {
                    ViewData["NhapMKXN"] = "Phải nhập mật khẩu xác nhận";
                }

                else
                {
                    foreach (var item in dblist)
                    {
                        if (item.tendangnhap == tendangnhap)
                        {
                            ViewData["existtk"] = "Tên tài khoản đã tồn tại";
                            break;
                        }

                        else if (item.email == email)
                        {
                            ViewData["existemail"] = "Email đã được sử dụng cho tài khoản khác";
                            break;
                        }

                        else if (!matkhau.Equals(MatKhauXacNhan))
                        {
                            ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận phải giống nhau";
                        }



                        else if ((DateTime.Now.Year - DateTime.Parse(ngaysinh.ToString()).Year) < 18)
                        {
                            ViewData["calcns"] = "Khách hàng phải đảm bảo đủ 18 tuổi";
                        }

                        else
                        {
                            kh.hoten = hoten;
                            kh.tendangnhap = tendangnhap;
                            kh.matkhau = matkhau;
                            kh.email = email;
                            kh.diachi = diachi;
                            kh.dienthoai = dienthoai;
                            kh.ngaysinh = DateTime.Parse(ngaysinh);
                            kh.RoleID = 2;
                            kh.status = 1;

                            data.KhachHangs.InsertOnSubmit(kh);
                            data.SubmitChanges();

                            return RedirectToAction("DangNhap");
                        }
                    }

                }
            }

            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();

        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau1 = collection["matkhau"];

            var matkhau = Encryptor.EncryptMD5(matkhau1);

            KhachHang kh =
                data.KhachHangs.FirstOrDefault(n => n.tendangnhap == tendangnhap && n.matkhau == matkhau);

            if (kh != null)
            {
                Session["TaiKhoan"] = kh;
                Session["Username"] = tendangnhap;

                if (kh.RoleID == 1)
                {
                    Session["Admin"] = kh;
                    return RedirectToAction("Index", "Admin");
                }
                else if (kh.RoleID == 3)
                {
                    Session["Staff"] = kh;
                    return RedirectToAction("Index", "Admin");
                }
                else if (kh.status == 2)
                {
                    ViewData["blockAccount"] = "Tài khoản của bạn đã bị khóa do có hành vi bất thường";
                    Session["TaiKhoan"] = null;
                    Session["Username"] = null;
                    return View();
                }

                else
                {
                    return RedirectToAction("ListSanPham", "SanPham");
                }

            }
            else
            {
                ViewBag.msg = "Tên đăng nhập hoặc mật khẩu không chính xác";
                return View();
            }

        }

        public ActionResult DangXuat()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            Session.Clear();
            return RedirectToAction("ListSanPham", "SanPham");
        }


        [HttpPost]
        public void SendVerificationLinkEmail(string emailID, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/NguoiDung/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("kjitvaf4@gmail.com", "PetStore");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "123456789Abc";

            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "Tai khoan da duoc tao thanh cong";
                body = "chua lam";
            }
            else if (emailFor == "ResetPassword")
            {
                subject = "Reset password";
                body = "Bạn vừa gửi link xác thực tài khoản, Hãy click vào link bên dưới để lấy lại mật khẩu<br>" +
                    "<a href=" + link + ">Reset password</a>";
            }

            /*var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);*/
            /*smtp - mail.outlook.com*/

            MailMessage mc = new MailMessage(System.Configuration.ConfigurationManager.AppSettings["Email"].ToString(), emailID);
            mc.Subject = subject;
            mc.Body = body;
            mc.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient("smtp.office365.com", 587);
            smtp.Timeout = 1000000;
            //smtp.Timeout = 1000;
            smtp.EnableSsl = true;
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            NetworkCredential nc = new NetworkCredential(System.Configuration.ConfigurationManager.AppSettings["Email"].ToString(), System.Configuration.ConfigurationManager.AppSettings["Password"].ToString());
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = nc;
            smtp.Send(mc);

        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string EmailID)
        {
            string message = "";
            MyDataDataContext data = new MyDataDataContext();
            var account = data.KhachHangs.Where(a => a.email == EmailID).FirstOrDefault();
            if (account != null)
            {
                string resetCode = Guid.NewGuid().ToString();
                SendVerificationLinkEmail(account.email, resetCode, "ResetPassword");
                account.resetpasswordcode = resetCode;

                data.SubmitChanges();

                message = "Reset password link đã được gửi đến email của bạn";
            }
            else
            {
                message = "Email không tồn tại";
            }
            ViewBag.Message = message;
            return View();
        }

        public ActionResult ResetPassword(string id)
        {
            MyDataDataContext data = new MyDataDataContext();
            var user = data.KhachHangs.Where(a => a.resetpasswordcode == id).FirstOrDefault();
            if (user != null)
            {
                ResetPasswordModel model = new ResetPasswordModel();
                model.ResetCode = id;
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]

petstore/Controllers/XemLichHenController.cs
using petstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace petstore.Controllers
{
    public class XemLichHenController : Controller
    {
        // GET: XemLichHen
        MyDataDataContext data = new MyDataDataContext();

       
        public ActionResult Index()
        {
            var all_danhmuc = from dv in data.DichVus
                              join kh in data.KhachHangs on dv.makh equals kh.makh
                              where kh.tendangnhap == Session["Username"]
                              select dv;

            return View(all_danhmuc);
        }


        public ActionResult HuyDichVu(int id)
        {
            var D_sach = data.DichVus.First(m => m.iddichvu == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult HuyDichVu(int id, FormCollection collection)
        {
            try
            {
                var D_danhmuc2 = data.DichVus.Where(m => m.iddichvu == id).First();

                if (D_danhmuc2.trangthai == "đang chờ")
                {

                    data.DichVus.DeleteOnSubmit(D_danhmuc2);
                    data.SubmitChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["thongbao1"] = "<script>alert('Đã tiếp nhận thông tin khách hàng không được xóa');</script>";

                    return RedirectToAction("Index");
                }
            }
            catch (Exception e) { return View("Error" + e); }


        }
    }
}

petstore/Controllers/XemLiveStreamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using petstore.Models;
namespace petstore.Controllers
{
    public class XemLiveStreamController : Controller
    {
        // GET: XemLiveStream

        public ActionResult Index()
        {
            MyDataDataContext data = new MyDataDataContext();
            var D_sach = data.LiveStreams.OrderByDescending(a => a.idLiveStream).ToList();
            return View(D_sach);
        }
    }
}

petstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản lý cửa hàng thú cưng</title>
    <link rel="shortcut icon" type="image/png" href="~/Content/images/logo.jpg" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/css/style.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />

</head>
<body>
    <div class="header">

        <div class="navbar">
            <div class="navbar__left">
                <a href="@Url.Action("ListSanPham", "SanPham")" class="navbar__logo">
                    <img src="~/Content/images/logo.jpg" alt="">
                </a>

                <div class="navbar__menu">
                    <i id="bars" class="fa fa-bars" aria-hidden="true"></i>
                    <ul class="navmenu">
                        <li><a href="/">Trang chủ</a></li>

                        <li><a href="@Url.Action("SanPham", "SanPham")">Sản phẩm</a></li>
                        <li><a href="@Url.Action("Index", "Home")">Dịch vụ</a></li>

                        @if (Session["TaiKhoan"] != null)
                        {
                            <li>
                                <a href="@Url.Action("Index", "XemDonHang")">Đơn hàng</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "XemLichHen")">Xem Lịch Hẹn</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "XemLiveStream")">Xem LiveStream</a>
                            </li>
                        }
                    </ul>
                </div>

            </div>

            <div class="navbar__center">

                @using (Html.BeginForm("TimKiem", "TimKiem", FormMethod.Get, new { @class = "navbar__search", @id = "formSearch" }))
                {
                    @Html.TextBox("search", null, new { @class = "search", @id = "message", placeholder = "Nhập để tìm kiếm", required = "required" })
                    <i id="btnTalk" class="fa-solid fa-microphone"></i>
                    <i class="fa fa-search" id="searchBtn"></i>

                }

            </div>

            <div class="navbar__right">
                <div style="display: flex; align-items: center;">

                    @if (Session["TaiKhoan"] != null)
                    {
                        <span>@Session["Username"].ToString()</span>


                        <a href="@Url.Action("DangXuat", "NguoiDung")">
                            <span class="fas fa-sign-out-alt"></span>
                        </a>
                    }
                    else
                    {
                        <div class="login">
                            <a href="@Url.Action("DangNhap", "NguoiDung")"><i class="fa fa-user"></i></a>
                        </div>
                    }

                </div>
                @Html.Action("GioHangPartial", "GioHang", new { @class = "giohang" })

            </div>
        </div>

    </div>


    @RenderBody()
    <footer>
        <div class="footer">
            <div class="footer__title">
                <span>Liên hệ</span>
                <div class="footer__social">
                    <a href="facebook.com/trieuetam" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-github"></i></a>
                    <a href="#"><i class="fab fa-google"></i></a>
                </div>
            </div>
        </div>

        <div class="footer__info">

            <div class="footer__info-content">
                <h3>Giới thiệu</h3>
                <p>Website quản lý, mua bán thú cưng</p>
            </div>



            <div class="footer__info-content">
                <h3>Liên hệ</h3>
                <p>Địa chỉ: 475 Điện Biên Phủ, Hutech khu A,B</p>
                <p>Email: trieuetam@gmail.com</p>
                <p>Sđt: 123456789</p>
            </div>

            <div class="footer__info-content">
                <h3>Fanpage</h3>
                <img width="315" src="~/Content/images/page.PNG" />
            </div>

        </div>

        <div class="footer__copyright">
            <center> 2022 All rights reserved.</center>
        </div>
    </footer>
    <div class="go-to-top"><i class="fas fa-chevron-up"></i></div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/scripts/ckfinder/ckfinder.js"></script>
    <script src="~/Content/scripts/ckeditor/ckeditor.js"></script>
    @RenderSection("upload", required: false)
    @RenderSection("scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script>
        //Slider using Slick
        $(document).ready(function () {
            $('.post-wrapper').slick({
                slidesToScroll: 1,
                autoplay: true,
                arrow: true,
                dots: true,
                autoplaySpeed: 5000,
                prevArrow: $('.prev'),
                nextArrow: $('.next'),
                appendDots: $(".dot"),
            });
        });

        // Slick mutiple carousel
        $('.post-wrapper2').slick({
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
            prevArrow: $('.prev2'),
            nextArrow: $('.next2'),
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 3,
                        infinite: true,
                    }
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 2
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                }
            ]
        });


        //Chat bang giong noi
        var message = document.querySelector('#message');

        var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition;
        var SpeechGrammarList = SpeechGrammarList || webkitSpeechGrammarList;

        var grammar = '#JSGF V1.0;'

        var recognition = new SpeechRecognition();
        var speechRecognitionList = new SpeechGrammarList();
        speechRecognitionList.addFromString(grammar, 1);
        recognition.grammars = speechRecognitionList;
        recognition.lang = 'vi-VN';
        recognition.interimResults = true;

        recognition.onresult = function (event) {
            var lastResult = event.results.length - 1;
            var content = event.results[lastResult][0].transcript;

            //hien thi giong noi ra input
            var productBrandField = $('input[name="search"]');
            productBrandField.val(content.replace('.', ''));
        };

        recognition.onspeechend = function () {
            recognition.stop();
        };

        recognition.onerror = function (event) {
            message.textContent = 'Đã xảy ra lỗi khi nhận dạng giọng nói: ' + event.error;
        }

        document.querySelector('#btnTalk').addEventListener('click', function () {
            recognition.start();
            //document.querySelector('#btnStop').classList.add('btnStopActive');
        });

        $("#message").on("keydown", function search(e) {
            if (e.keyCode == 13) {
                var input = document.getElementById("message").value

                searchHistory(input)

                const cat = localStorage.getItem('searchHistory');

                setCookie('searchname', encodeURIComponent(cat), 7);
            }
        });

        function setCookie(name, value, days) {
            var expires = "";
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "") + expires + "; path=/";
        }

        const localGet = localStorage.getItem('searchHistory') || '["chó","chó","chó"]'

        function searchHistory(inpu) {
            const maxHistoryLength = 3;
            
            const history = JSON.parse(localGet);
            const isHistoryMaxed = history.length === maxHistoryLength;
            const workingHistory = isHistoryMaxed ? history.slice(1) : history;
            const updatedHistory = workingHistory.concat(inpu);

            localStorage.setItem('searchHistory', JSON.stringify(updatedHistory));
        }


    </script>


    <script src="~/Content/scripts/script.js"></script>
</body>
</html>