petstore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using petstore.Models;
using PagedList;
using System.IO;

using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;

namespace petstore.Controllers
{
    public class AdminController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();


        public ActionResult Index()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            ViewBag.Online = HttpContext.Application["Online"].ToString();

            ViewBag.TongDoanhThu = ThongKeDoanhThu();
            ViewBag.TongDDH = ThongKeDonHang();
            ViewBag.TongKhachHang = ThongKeKhachHang();

            List<int> rep = new List<int>();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            List<SanPham> sanpham = data.SanPhams.ToList();

            //---------------- BIEU DO COT-------------------
            var listsp = sanpham.Select(x => x.masp).Distinct().Take(10); //lay ra danh sach ma sp
            var listsp2 = sanpham.Select(x => x.tensp).Distinct().Take(10);
            foreach (var item in listsp)
            {
                rep.Add((int)ctdh
                    .Where(x => x.masp == item && x.status == 1)
                    .Sum(x => x.soluong * x.gia)); //duyet ds ma don roi in ra tong tien tung ma sp
                                                   //.Count(x =>x.soluong == item));
            }

            ViewBag.AGES = listsp2;
            ViewBag.REP = rep.ToList().Take(10);
            //----------------

            return View();
        }

        //-----------------------------------DOANH THU --------------------------------------------
        #region  
        public ActionResult DoanhThu()
        {
            ViewBag.TongDoanhThu = ThongKeDoanhThu();

            var getlist = data.SanPhams.ToList();
            SelectList list = new SelectList(getlist, "masp", "tensp");

            return View();
        }

        public ActionResult DoanhThuNgay(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            var getDay = DateTime.Parse(ngaygiao.ToString()).Day;
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Ngay = getDay;
            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuNgay = ThongKeDoanhThuNgay(getDay, getMonth, getYear);
            ViewBag.DoanhThuNgayCount = ThongKeDoanhThuNgayCount(getDay, getMonth, getYear);

            //ViewBag.CountDTN = ThongKeCountDoanhThuNgay(getDay, getMonth, getYear);


            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Day == getDay && sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }

        public ActionResult DoanhThuThang(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuThang = ThongKeDoanhThuThang(getMonth, getYear);
            ViewBag.DoanhThuThangCount = ThongKeDoanhThuThangCount(getMonth, getYear);

            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }

        public ActionResult DoanhThuNam(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Nam = getYear;
            ViewBag.DoanhThuNam = ThongKeDoanhThuNam(getYear);
            ViewBag.DoanhThuNamCount = ThongKeDoanhThuNamCount(getYear);

            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }

        public int Countrate(int id)
        {
            List<SanPham> sanpham = data.SanPhams.ToList();
            List<DanhGia> danhgia = data.DanhGias.ToList();
            int CountRate = (from dg in danhgia
                             join sp in sanpham
                             on dg.id_sp equals sp.masp
                             where (dg.id_sp == id && dg.id_sp == sp.masp && dg.Rating == 5)
                             select new ViewModel
                             {
                                 danhgia = dg,
                                 sanpham = sp
                             }).Count();
            return CountRate;
        }


        public decimal ThongKeDoanhTungSanPhamChoGia(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong * n.gia)
            ).Value;
            return TongDoanhThu;
        }

        public decimal ThongKeDoanhTungSanPhamChoSL(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong)
            ).Value;
            return TongDoanhThu;
        }

        public decimal ThongKeDoanhThu()
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.status == 1)
                .Sum(
                n => n.soluong * n.gia
            ).Value;
            return TongDoanhThu;
        }

        public decimal ThongKeDoanhThuNgay(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }

        public decimal ThongKeDoanhThuNgayCount(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong).Value.ToString()
                );
            }
            return tongtien;
        }

        public decimal ThongKeDoanhThuThang(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }

        public decimal ThongKeDoanhThuThangCount(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs

petstore/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using petstore.Models;

namespace petstore.Controllers
{
    public class DanhMucController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: DanhMuc
        //---------Index-DanhMuc------------
        public ActionResult Index()
        {
            var all_danhmuc = from tt in data.DanhMucs select tt;
            return View(all_danhmuc);
        }

        //---------Detail-DanhMuc------------

        public ActionResult Details(int id)
        {
            var Data_danhmuc = data.DanhMucs.Where(m => m.idDanhmuc == id).First();
            return View(Data_danhmuc);
        }

        //---------Create(tao moi the loai sach)-DanhMuc------------
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, DanhMuc tl)
        {
            var ten = collection["tendanhmuc"];
            var ParentID = collection["ParentID"];

            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                tl.tendanhmuc = ten;
                if (ParentID == "")
                {
                    ParentID = null;
                }
                tl.ParentID = ParentID;
                data.DanhMucs.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        //---------Edit-DanhMuc------------

        public ActionResult Edit(int id)
        {
            var E_category = data.DanhMucs.First(m => m.idDanhmuc == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var danhmuc = data.DanhMucs.First(m => m.idDanhmuc == id);
            var E_tendanhmuc = collection["tendanhmuc"];
            danhmuc.idDanhmuc = id;
            if (string.IsNullOrEmpty(E_tendanhmuc))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                danhmuc.tendanhmuc = E_tendanhmuc;
                UpdateModel(danhmuc);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        //---------Delete------------

        public ActionResult Delete(int id)
        {
            var D_danhmuc = data.DanhMucs.First(m => m.idDanhmuc == id);
            return View(D_danhmuc);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var D_danhmuc = data.DanhMucs.Where(m => m.idDanhmuc == id).First();
                data.DanhMucs.DeleteOnSubmit(D_danhmuc);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e) { return View("Error" + e); }

        }

    }
}

petstore/Views/DanhMuc/Create.cshtml
@model petstore.Models.DanhMuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="menu_option-head2">Thêm danh mục</div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-md-2" for="tendanhmuc">Tên danh mục (*)</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tendanhmuc, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.tendanhmuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-2">
                    @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "" })
                    <span>(Không bắt buộc)</span>
                </div>

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ParentID, new { htmlAttributes = new { @class = "form-control", @placeholder = "Danh mục cha" } })
                    @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index", "Admin", new { @class = "btn btn-default mt-2" })
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

petstore/Views/DanhMuc/Delete.cshtml
@model petstore.Models.DanhMuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 p-4">

    <dl class="dl-horizontal">
        <div class="menu_option-head2">Xóa danh mục</div>
        <hr />
        <div>
            <strong>@Html.DisplayNameFor(model => model.tendanhmuc)</strong>
        </div>

        <div>
            @Html.DisplayFor(model => model.tendanhmuc)
        </div>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Quay lại", "Index", "Admin", new { @class = "btn btn-default" })
    </div>
    }
</div>



petstore/Views/DanhMuc/Details.cshtml
@model petstore.Models.DanhMuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    <dl class="dl-horizontal">
        <div class="menu_option-head2">Chi tiết</div>
        <hr />
        <div>
            <strong>Tên danh mục</strong>
        </div>

        <div>
            @Html.DisplayFor(model => model.tendanhmuc)
        </div>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.idDanhmuc }) |
        @Html.ActionLink("Quay lại", "Index")
    </p>
</div>

petstore/Views/DanhMuc/Edit.cshtml
@model petstore.Models.DanhMuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="menu_option-head2 pl-2 pt-2">Sửa sản phẩm</div>
            <hr />
            <table class="table">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idDanhmuc)

                <div class="form-group">
                    <label class="col-md-2" for="tendanhmuc">Tên danh mục (*)</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.tendanhmuc, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.tendanhmuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "" })
                        <span>(Không bắt buộc)</span>
                    </div>

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ParentID, new { htmlAttributes = new { @class = "form-control", @placeholder = "Danh mục cha" } })
                        @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </table>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index", "Admin", new { @class = "btn btn-default ml-2" })
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

petstore/Views/DanhMuc/Index.cshtml
@model IEnumerable<petstore.Models.DanhMuc>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 p-2 pl-4">

    <div class="body fix-width scroll-inner">
        <table class="table table-striped">
            <div class="menu_option-head">Danh Mục Sản Phẩm</div>
            <div class="add-product">
                <a href="@Url.Action("Create")">Thêm danh mục</a>
            </div>

            <thead>
            <th>ID</th>
            <th>Tên Danh Mục</th>
            <th>
                Chức năng
            </th>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.idDanhmuc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tendanhmuc)
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "DanhMuc", new { id = item.idDanhmuc })" class="text-primary f2"><i class="fa-solid fa-eye"></i></a>
                        <a href="@Url.Action("Edit", "DanhMuc", new { id = item.idDanhmuc })" class="text-primary f2"><i class="fas fa-edit"></i></a>
                        <a href="@Url.Action("Delete", "DanhMuc", new { id = item.idDanhmuc })" class="text-primary f2"><i class="fa-solid fa-trash-can"></i></a>
                    </td>
                </tr>
            }

        </table>

    </div>

    <div>
        @Html.ActionLink("Quay lại", "Index", "Admin", new { @class = "btn btn-default mt-2" })
    </div>

    </div>

    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
    <style type="text/css">
        #mau-nut a {
            clear: both;
            background-color: orange;
            color: snow;
        }

            #mau-nut a:hover {
                background-color: darkcyan;
                color: snow;
            }
    </style>
